language: ruby
cache: bundler

# Travis will build the site from gh-pages branch
# and deploy the content to master branch
# use gh-pages branch to serve for github pages
# master branch will be used for deployment

branches:
  only:
  - gh-pages
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site

# You need to generate a Personal Access Token
# https://github.com/settings/tokens
# Add this token in environment variable GITHUB_TOKEN in Travis CI repo settings

deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  email: kumar289@gmail.com
  name: Phaneendra
  skip-cleanup: true
  github-token: a74e608e09f3233fc2f3c5c9d4ce0c3222eaef8b
  keep-history: true
  on:
    branch: gh-pages

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
  gem install travis
  travis encrypt 'GIT_NAME="PhaneendraGunda" GIT_EMAIL="kumar289@gmail.com" GH_TOKEN="a74e608e09f3233fc2f3c5c9d4ce0c3222eaef8b" --add env.global --com

# env:
#   global:
#     secure: Example