title: Phaneendra kumar
# subtitle: A Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://PhaneendraGunda.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
# baseurl: "/blog" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: AI Resources
      url: /resources
    - text: Blog
      url: /blog
    # - text: Resume
    #   url: /resume
    - text: Gallery
      url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact Me
      url : /contact
    # - text: Styleguide
      # url: /styleguide
    # - text: Get Started
      # url: /get-started

# Edit these details

author_logo_formal: myphoto-formal.jpg
author_logo_casual: myphoto-casual.jpg
author: Phaneendra Kumar
author_bio: Technology Enthusiast, Travelling, Cooking, Movies
author_email: "kumar289@gmail.com"
author_location: Bangalore, India
author_website_url: "https://PhaneendraGunda.github.io"
typewrite-text: Hello folks, welcome to Machine Learning blog !!!

author_work_experiences:
            - company_name: Oracle
              company_logo: oracle.png
              company_url: https://oracle.com
              designation: Senior Data Scientist
              description: Working on ML and NLP initiatives
              visibility: true
            - company_name: Xoriant
              company_logo: xoriant.jpg
              company_url: https://www.xoriant.com/
              designation: Senior Data Scientist
              description: Worked on ML and NLP initiatives
              visibility: true
            - company_name: Wipro
              company_logo: wipro.jpg
              company_url: https://www.wipro.com/holmes/
              designation: Data Scientist
              description: Worked on ML and NLP initiatives in Wipro Holmes
              visibility: true
            - company_name: Rockwell Collins
              company_logo: rockwell.jpeg
              company_url: https://www.collinsaerospace.com/
              designation: Senior Software Engineer
              description: Worked on Headp Up and Head Down Displays
              visibility: true

author_education_details:
              - college_logo: cdac.jpeg
                college_name: C-DAC
                college_url: https://www.cdac.in/
                description: PG Diploma In Embedded Systems and Design (PG-DESD)
                visibility: true
              - college_logo: jntu.jpg
                college_name: JNTU
                college_url: https://www.jntuk.edu.in/
                description: Bachelor of Technology
                visibility: true

author_certifications:
              - certificate_logo: udemy.png
                certificate_issuer: Udemy
                certificate_url: https://www.udemy.com/certificate/UC-P8H5WY5J/
                certificate_title: Deep Learning with PyTorch
                visibility: true      
              - certificate_logo: deeplearning-ai.png
                certificate_issuer: Cousera
                # certificate_url: https://www.udemy.com/certificate/UC-P8H5WY5J/
                certificate_title: Deep Learning Specialisation
                visibility: true 

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

courses:
      - course_name: Machine Learning
        course_author: By Andrew Ng
        course_inistitute: Coursera
        course_logo: Coursera.jpeg
        course_url: https://www.coursera.org/learn/machine-learning
      - course_name: Deep Learning Specialisation
        course_author: By Andrew Ng
        course_inistitute: deeplearning.ai
        course_logo: deeplearning-ai.png
        course_url: https://www.deeplearning.ai/deep-learning-specialization/
      - course_name: NLP with Deep Learning
        course_author: By Chris Manning
        course_inistitute: Stanford
        course_logo: stanford.png
        course_url: http://web.stanford.edu/class/cs224n/
      - course_name: Practical Deep Learning
        course_author: By Jeremy Howard
        course_inistitute:  Fast.ai
        course_logo: fast-ai.png
        course_url: https://course.fast.ai/index.html
      - course_name: The Python Tutorial
        course_author: By Python.org
        course_inistitute:  Python.org
        course_logo: python.jpeg
        course_url: https://docs.python.org/3/tutorial/
      - course_name: Linear Algebra
        course_author: by MIT Prof. Gilbert Strang
        course_inistitute:  MIT
        course_logo: mit.png
        course_url: https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/
      - course_name: Linear Algebra
        course_author: By Khan Academy
        course_inistitute: Khan Academy
        course_logo: khan-academy.png
        course_url: https://www.khanacademy.org/math/linear-algebra
      - course_name: Statistics and Probability
        course_author: By Khan Academy
        course_inistitute: Khan Academy
        course_logo: khan-academy.png
        course_url: https://www.khanacademy.org/math/statistics-probability

blogs:
    - author: Andrej Karpathy blog
      url : http://karpathy.github.io/
    - author: Machine Learning Mastery
      url : https://machinelearningmastery.com/blog/
    - author: Towards Data Science
      url : https://towardsdatascience.com/
    - author: Christopher Olah
      url : http://colah.github.io/
    - author: Made with ML
      url : https://madewithml.com/
    - author: I am trask
      url : http://iamtrask.github.io/
    - author: Wild ML
      url : http://www.wildml.com/
    - author: Depends on the definition
      url : https://www.depends-on-the-definition.com/
    - author: Sebastian Ruder
      url : https://ruder.io/
    - author: Artificial Intellegence Wiki
      url : https://pathmind.com/wiki/
    - author: Chris McCormick 
      url: http://mccormickml.com/archive/
    - author: Luis Serrano's Blog
      url: https://serrano.academy/

github_projects:
              - name: Keras Idiomatic Programmer
                url: https://github.com/GoogleCloudPlatform/keras-idiomatic-programmer
              - name: Fast book from Fast.ai
                url: https://github.com/fastai/fastbook
              - name: A carefully curated list of NLP paper summaries
                url: (https://github.com/dair-ai/nlp_paper_summaries
              - name: Progress in Natural Language Processing (NLP)
                url: https://github.com/sebastianruder/NLP-progress

cheat_sheets:
          - name: Python for DS cheat sheet
            url: http://www.utc.fr/~jlaforet/Suppl/python-cheatsheets.pdf
          - name: Machine Learning cheat sheet
            url: https://stanford.edu/~shervine/teaching/cs-229/
          - name: PyTorch cheat sheet
            url: https://pytorch.org/tutorials/beginner/ptcheat.html


Datasets:
        - name: UCI Machine Learning Repository
          url: http://archive.ics.uci.edu/ml/index.php
        - name: Kaggle Datasets
          url: https://www.kaggle.com/datasets
        - name: Google Dataset Search
          url: https://datasetsearch.research.google.com/
        - name: World Bank Open Data
          url: https://data.worldbank.org/


books:
    - name: François Chollet
      url: https://livebook.manning.com/book/deep-learning-with-python?origin=product-look-inside
    - name: Natural Language Processing with Python
      url: https://github.com/ShawnLeee/the-book/blob/master/pybooks/Natural%20Language%20Processing%20with%20Python.pdf


# social links
github_username:  PhaneendraGunda
facebook_username: Phaneendra.kumar.Gunda
linkedin_username: phaneendra-kumar-gunda-a21b7b32

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: PhaneendraGunda

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: kumar289@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
# google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false
show_certifications: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
